package com.siteflow.reliability;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.not;
import static org.hamcrest.Matchers.notNullValue;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

@SpringBootTest
@AutoConfigureMockMvc
class HealthAndObservabilityTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired(required = false)
    private com.siteflow.security.ratelimit.RateLimiterService rateLimiterService;

    @org.junit.jupiter.api.BeforeEach
    void resetRateLimiter() {
        if (rateLimiterService != null) {
            rateLimiterService.resetAll();
        }
    }

    @Test
    @DisplayName("Health endpoint is accessible without authentication and reports UP")
    void healthEndpoint_isPubliclyAccessibleAndReportsUp() throws Exception {
        mockMvc.perform(get("/actuator/health"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status").value("UP"));
    }

    @Test
    @DisplayName("Health endpoint does not expose sensitive database or infrastructure details")
    void healthEndpoint_doesNotExposeSensitiveDetails() throws Exception {
        MvcResult result = mockMvc.perform(get("/actuator/health"))
                .andExpect(status().isOk())
                .andReturn();

        String content = result.getResponse().getContentAsString();
        // Safe configuration must not expose internal components, queries, or credentials
        assertThat(content).doesNotContain("database");
        assertThat(content).doesNotContain("validationQuery");
        assertThat(content).doesNotContain("password");
        assertThat(content).doesNotContain("username");
        assertThat(content).doesNotContain("jdbc");
        assertThat(content).doesNotContain("diskSpace");
        assertThat(content).doesNotContain("ping");
        // Only safe status and groups should be visible
        assertThat(content).contains("\"status\":\"UP\"");
        assertThat(content).doesNotContain("diskSpace");
        assertThat(content).doesNotContain("components");
    }

    @Test
    @DisplayName("X-Request-ID is automatically generated when not provided in request")
    void correlationId_autoGeneratedWhenOmitted() throws Exception {
        MvcResult result = mockMvc.perform(get("/actuator/health"))
                .andExpect(status().isOk())
                .andExpect(header().exists("X-Request-ID"))
                .andReturn();

        String requestId = result.getResponse().getHeader("X-Request-ID");
        assertThat(requestId).isNotBlank();
        // Should be a valid UUID format (36 chars with hyphens)
        assertThat(requestId).matches("^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$");
    }

    @Test
    @DisplayName("X-Request-ID is preserved and echoed back when provided by client")
    void correlationId_preservedWhenProvided() throws Exception {
        String clientRequestId = "req-client-trace-789";

        mockMvc.perform(get("/actuator/health")
                        .header("X-Request-ID", clientRequestId))
                .andExpect(status().isOk())
                .andExpect(header().string("X-Request-ID", clientRequestId));
    }

    @Test
    @DisplayName("X-Request-ID sanitizes invalid characters and replaces with safe UUID")
    void correlationId_sanitizesInvalidCharacters() throws Exception {
        String invalidHeader = "invalid id with spaces and $ymb@ls!!!";

        MvcResult result = mockMvc.perform(get("/actuator/health")
                        .header("X-Request-ID", invalidHeader))
                .andExpect(status().isOk())
                .andExpect(header().exists("X-Request-ID"))
                .andReturn();

        String responseHeader = result.getResponse().getHeader("X-Request-ID");
        // Malicious / invalid string must be rejected and replaced with safe UUID
        assertThat(responseHeader).isNotEqualTo(invalidHeader);
        assertThat(responseHeader).matches("^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$");
    }

    @Test
    @DisplayName("Error response includes requestId matching X-Request-ID")
    void errorResponse_includesMatchingRequestId() throws Exception {
        String customId = "trace-err-400-xyz";

        // POST invalid malformed JSON to /api/auth/login to trigger GlobalExceptionHandler
        mockMvc.perform(post("/api/auth/login")
                        .header("X-Request-ID", customId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"username\": }")) // invalid json
                .andExpect(status().isBadRequest())
                .andExpect(header().string("X-Request-ID", customId))
                .andExpect(jsonPath("$.status").value("error"))
                .andExpect(jsonPath("$.data.requestId").value(customId))
                .andExpect(jsonPath("$.data.status").value(400))
                .andExpect(jsonPath("$.data.path").value("/api/auth/login"));
    }

    @Test
    @DisplayName("Server error does not leak credentials or stack trace to client")
    void errorResponse_doesNotLeakCredentialsOrSensitiveInfo() throws Exception {
        MvcResult result = mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"username\":\"admin\", \"password\":\"secret-pwd-attempt\"}"))
                .andExpect(status().isUnauthorized())
                .andReturn();

        String content = result.getResponse().getContentAsString();
        assertThat(content).doesNotContain("secret-pwd-attempt");
        assertThat(content).doesNotContain("Shizukusan");
        assertThat(content).doesNotContain("root");
        assertThat(content).doesNotContain("Exception");
        assertThat(content).doesNotContain("at com.siteflow");
    }
}
