spring:
  application:
    name: siteflow
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:siteflow}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Shizukusan1412
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: ${SERVER_PORT:8080}
