-- =========================================================================
-- V3: Seed Users (Deprecated from Core Production Migration Chain)
--
-- Security notice:
-- Development and demo credentials have been isolated from the production
-- Flyway migration chain to ensure fresh production environments fail closed
-- without default passwords.
--
-- Dev demo fixtures are located in: db/dev-seed/R__dev_seed_users.sql (dev profile)
-- Test fixtures are located in: db/test-fixtures/R__test_seed_users.sql (test profile)
-- Production administrators must be explicitly provisioned via AdminProvisioningRunner
-- or scripts/provision-admin.sh.
-- =========================================================================
